# Generated by Django 4.2.23 on 2025-09-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact'),
        ),
    ]
