# Generated by Django 4.2.23 on 2025-09-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom complet'),
        ),
    ]
