# Generated by Django 4.2.23 on 2025-09-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='À propos de TLMT Services', max_length=255)),
                ('description', models.TextField()),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='apropos/')),
            ],
        ),
        migrations.CreateModel(
            name='PourquoiChoisir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('apropos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_cles', to='apropos.apropos')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureApropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='apropos/features/')),
                ('apropos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='apropos.apropos')),
            ],
        ),
    ]
