# Generated by Django 4.2.23 on 2025-09-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apropos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pourquoichoisir',
            name='apropos',
        ),
        migrations.DeleteModel(
            name='FeatureApropos',
        ),
        migrations.DeleteModel(
            name='PourquoiChoisir',
        ),
    ]
