# Generated by Django 4.2.23 on 2025-09-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apropos', '0002_remove_pourquoichoisir_apropos_delete_featureapropos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apropos',
            name='features_descriptions',
            field=models.TextField(blank=True, help_text='Descriptions des features, un par ligne', null=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='features_images',
            field=models.TextField(blank=True, help_text='URLs/images des features, un par ligne (optionnel)', null=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='features_titres',
            field=models.TextField(blank=True, help_text='Titres des features, un par ligne', null=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='points_cles',
            field=models.TextField(blank=True, help_text='Liste des points clés, un par ligne', null=True),
        ),
    ]
