# Generated by Django 4.2.23 on 2025-09-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apropos', '0003_apropos_features_descriptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apropos',
            name='features_descriptions',
        ),
        migrations.RemoveField(
            model_name='apropos',
            name='features_images',
        ),
        migrations.RemoveField(
            model_name='apropos',
            name='features_titres',
        ),
        migrations.RemoveField(
            model_name='apropos',
            name='points_cles',
        ),
        migrations.CreateModel(
            name='PointCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('apropos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_cles', to='apropos.apropos')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='apropos/features/')),
                ('apropos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='apropos.apropos')),
            ],
        ),
    ]
