# Generated by Django 4.2.23 on 2025-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDimensionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('jours_autonomie', models.IntegerField(default=3)),
                ('irradiation', models.FloatField(default=2.4, verbose_name='Irradiation (kWh/m².j)')),
                ('rendement_k', models.FloatField(default=0.65, verbose_name='Coefficient K')),
                ('appareils', models.TextField(blank=True, null=True)),
                ('energie_journaliere', models.FloatField(blank=True, null=True)),
                ('puissance_crete', models.FloatField(blank=True, null=True)),
                ('tension_systeme', models.FloatField(blank=True, null=True)),
                ('capacite_batterie', models.FloatField(blank=True, null=True)),
                ('puissance_onduleur', models.FloatField(blank=True, null=True)),
                ('panneaux_propositions', models.TextField(blank=True, default='[]')),
                ('batteries_propositions', models.TextField(blank=True, default='[]')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='dimensionements/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energie_journaliere', models.FloatField(blank=True, null=True)),
                ('coefficient_k', models.FloatField(blank=True, null=True)),
                ('irradiation', models.FloatField(blank=True, null=True)),
                ('puissance_totale_ac', models.FloatField(blank=True, null=True)),
                ('jours_autonomie', models.IntegerField(blank=True, null=True)),
                ('tension_systeme', models.FloatField(blank=True, null=True)),
                ('decharge_max', models.FloatField(blank=True, null=True)),
                ('puissance_crete', models.FloatField(blank=True, null=True)),
                ('capacite_batterie', models.FloatField(blank=True, null=True)),
                ('puissance_onduleur', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
