# Generated by Django 4.2.23 on 2025-09-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description_courte', models.TextField(blank=True, null=True)),
                ('description_detaillee', models.TextField(blank=True, null=True)),
                ('prix_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avis', models.PositiveIntegerField(default=0)),
                ('caracteristiques_raw', models.TextField(blank=True, default='[]')),
                ('couleurs_raw', models.TextField(blank=True, default='[]')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='article.categorie')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/')),
                ('principale', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='article.produit')),
            ],
            options={
                'verbose_name': 'Image de produit',
                'verbose_name_plural': 'Images de produit',
            },
        ),
    ]
