# Generated by Django 4.2.23 on 2025-09-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Caractéristique',
                'verbose_name_plural': 'Caractéristiques',
            },
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code_hex', models.CharField(blank=True, help_text='Ex: #FF0000', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
            },
        ),
        migrations.RemoveField(
            model_name='produit',
            name='caracteristiques_raw',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='couleurs_raw',
        ),
        migrations.AddField(
            model_name='produit',
            name='caracteristiques',
            field=models.ManyToManyField(blank=True, related_name='produits', to='article.caracteristique'),
        ),
        migrations.AddField(
            model_name='produit',
            name='couleurs',
            field=models.ManyToManyField(blank=True, related_name='produits', to='article.couleur'),
        ),
    ]
