# Generated by Django 5.2.7 on 2025-10-24 11:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_produit_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description_courte',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description_detaillee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
