# Generated by Django 3.2.5 on 2025-10-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='ordre',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
