# Generated by Django 5.2.7 on 2025-10-21 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_servicecomment_servicelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèces'), ('mvola', 'Mvola'), ('airtel', 'Airtel Money'), ('orange', 'Orange Money')], default='espece', max_length=20),
        ),
        migrations.AddField(
            model_name='servicecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.servicecomment'),
        ),
        migrations.CreateModel(
            name='CommandeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.commande')),
            ],
        ),
    ]
