# Generated by Django 5.2.7 on 2025-10-24 12:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_commande_mode_paiement_servicecomment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
