# Generated by Django 3.2.5 on 2025-10-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppareilSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('debit_brut', models.FloatField(help_text='Débit brut Qb en L/s')),
                ('eau_chaude', models.BooleanField(default=False, help_text="L'appareil utilise-t-il l'eau chaude ?")),
                ('image', models.ImageField(blank=True, null=True, upload_to='appareils/')),
            ],
        ),
    ]
