# Generated by Django 3.2.5 on 2025-10-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plomberie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionAppareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('appareil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plomberie.appareilsanitaire')),
            ],
        ),
    ]
